### ISSUE TITLE
Customize the options beyond YES vs NO

### ISSUE THREAD

**Issue by dreeves** [bsoule/Expectorant#13]
Or maybe this is too far outside the scope and we should first find a use case for generalizing beyond binary.

Use cases so far:

1. Flipping a weighted coin -- YES vs NO
2. Making exact change -- LOW vs HIGH
3. Restaurant bill splitting -- FREE vs PAY

So we could just label the green section "YES / PAY / HIGH" and the red section "NO / FREE / LOW" for now.

**Comment by morehavoc** [comment]
The spinner is currently labeled as such, just with emoji.
