### ISSUE TITLE
SVG breaks if p=1e-8

### ISSUE THREAD

**Issue by dreeves** [bsoule/Expectorant#18]
## Reseminata

1. Type in .00000001 or 1e-8 as the probability

## Expectata

That it look pretty similar to how 1e-7 looks, with an invisible sliver of a green slice on a red circle.

## Resultata

![image](https://user-images.githubusercontent.com/9928/207037239-ae001a10-7dab-4bb7-992d-b464fc0c5649.png)

Wheee!

**Comment by morehavoc** [comment]
This is b/c we are drawing arcs, and when you start drawing "arcs" that are full circles, things get all wonky. I think that we should limit the minimum probability (inside the spinner only) to be .01, or something like that. This way, it can draw it, and probably actually be visible to the user, even as a little green sliver. This should only be done within the spinner library, so it won't change the actual probabilities or the outcome, just how it's displayed.

**Comment by dreeves** [comment]
I fixed this! 🎉
