### ISSUE TITLE
Make the spinner reflect the probability

### ISSUE THREAD

**Issue by dreeves** [bsoule/Expectorant#6]
Whatever probability is in that box (use 50% by default if it's blank), that's what the spinner should reflect. In real time as you edit the probability.

## Desiderata

- [x] Do that
- [x] Pick something to display like a big "NaN" if what's in the box isn't a number between 0 and 1
- [x] Make a new gissue for generalizing to more than two outcomes

_**Verbata**: UI, ajax, dynamically reflecting the probability,_

**Comment by morehavoc** [comment]
Notes:
- Still spins even if NaN (probably shouldn't)
- Spin does not go to the specified destination (none is specified so far)
- You can update the expression while it's spinning and it updates the spinner... (probably should lock the text box?)
- Still want to highlight the one that wins when the spinner stops. When it starts, redraw it to remove the highlight?
- Remove `Spinner.html` when this is all working.
- Test on mobile
